apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036   # External port on each node (range 30000-32767)
  type: NodePort       # Exposes service on each Node's IP at the nodePort
